[package]
name = "xjyutping-tool"
version = "1.2.1"
description = "Jyutping teaching tool built on xjyutping"
authors = ["the xjyutping authors"]
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
